apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog
spec:
  global:
    clusterName: logistics-microservice
    site: datadoghq.eu
    kubelet:
      tlsVerify: false
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    tags:
      - "env:dev" # matches DD_ENV=dev on the services
  features:
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
        hostPort: 8126 # = DD_TRACE_AGENT_PORT on the services
    dogstatsd:
      hostPortConfig:
        enabled: true
        hostPort: 8125 # = DD_DOGSTATSD_PORT on the services
      originDetectionEnabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
    clusterChecks:
      enabled: true
    orchestratorExplorer:
      enabled: true
  override:
    nodeAgent:
      env:
        - name: DD_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
